In [2]:
import numpy as np
a=np.array([1,2,3,4])
type(a)


numpy.ndarray

In [3]:
a.ndim

1

In [4]:
a

array([1, 2, 3, 4])

In [5]:
a.dtype

dtype('int64')

In [7]:
a=np.array([1,2,3,4],dtype=float)
type(a)
a

array([1., 2., 3., 4.])

In [8]:
a=np.array([[2,23,43],[1,3,4]],ndmin=3)
a

array([[[ 2, 23, 43],
        [ 1,  3,  4]]])

In [9]:
a.ndim

3

In [10]:
dt=np.dtype('int64')
dt

dtype('int64')

In [11]:
a.astype('int64')

array([[[ 2, 23, 43],
        [ 1,  3,  4]]])

In [12]:
a.dtype

dtype('int64')

In [13]:
a=np.array(['a',2,4.6],dtype='object')
a

array(['a', 2, 4.6], dtype=object)

In [14]:
#tolist method, (Used to change to list)
a.tolist()

['a', 2, 4.6]

In [15]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr.shape

(2, 4)

In [16]:
arr.ndim

2

In [17]:
arr.dtype

dtype('int64')

In [18]:
arr.itemsize

8

In [19]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [20]:
from numpy import arange 
from timeit import Timer
n=10000
x=arange(n)
y=range(n)
tn=Timer("x.sum()","from __main__ import x")
tl=Timer("sum(y)","from __main__ import y")
tn.timeit(n)

0.10115398700000355

In [21]:
tl.timeit(n)

1.731147452000016

# methods to create an array

#### Using list and other data structures

In [22]:
l=[1,2,3,4]
a=np.array(l)
a

array([1, 2, 3, 4])

#### from numpy functions

#1. empty()
a=np.empty([3,2],dtype='int32)
a

In [23]:
a=np.empty([3,2],dtype='int32') 
a

array([[         0, 1072168960],
       [         0, 1072168960],
       [         0,          0]], dtype=int32)

In [24]:
a2=np.zeros([2,3])
a2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
a2=np.ones([2,3],dtype='int32')
a2

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [26]:
a2=np.full([2,3],5.6)
a2

array([[5.6, 5.6, 5.6],
       [5.6, 5.6, 5.6]])

In [27]:
a2.dtype

dtype('float64')

In [28]:
%%timeit 
np.empty(1000000)

The slowest run took 104.53 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 2 µs per loop


In [29]:
%%timeit 
np.ones(1000000)

The slowest run took 11.52 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 554 µs per loop


In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.identity(3)                #same as np.eye but has only two attributes

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.eye(4,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

###### Reshaping in array

In [33]:
a=np.arange(8)
print(a)

[0 1 2 3 4 5 6 7]


In [34]:
a2=a.reshape(2,4)
a2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [35]:
a3=a.reshape(4,2)
a3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [36]:
a3=a.reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
a3.shape

(2, 2, 2)

In [38]:
a3.reshape(-1).shape       #-1 changes in to (1,n)

(8,)

In [39]:
a3.shape

(2, 2, 2)

In [40]:
a3.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [41]:
a3.reshape(-2,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [42]:
a3.reshape(1,-1)

array([[0, 1, 2, 3, 4, 5, 6, 7]])

## CREATION OF ARRAY FROM EXISTING DATA

In [43]:
a=np.asarray(l)
a

array([1, 2, 3, 4])

### using from iter

In [45]:
it=iter(l)
ai=np.fromiter(it,dtype=int)
ai

array([1, 2, 3, 4])

### array from numerical ranges

In [46]:
a=np.arange(0,100,5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [47]:
a=np.linspace(0,10,10,endpoint=False)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [48]:
a=np.logspace(1,10,num=9,base=2)                 #num specifies number of elements, by default base is e
a

array([   2.        ,    4.36203093,    9.51365692,   20.74943287,
         45.254834  ,   98.70149283,  215.2694823 ,  469.50607012,
       1024.        ])

## Array indexing and slicing

In [49]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a[1,...]

array([4, 5, 6])

In [50]:
a=np.fromfunction(lambda i,j:i+j,(3,3))
a

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

## Boolean indexing

In [51]:
a=np.arange(1,10)
a=a.reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
a[a>5]

array([6, 7, 8, 9])

#### broadcasting

In [53]:
a=np.arange(1,10)
a=a.reshape(3,3)
b=np.arange(1,4)
print(a)
print(b)
a+b

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

## transpose function

In [54]:
a=np.arange(1,10)
a=a.reshape(3,3)
a.transpose()


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [55]:
a=np.arange(0,4)
a=a.reshape(4,1)
b=np.arange(0,3).reshape(1,3)
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

# linear algebra

In [56]:
a=np.arange(1,10)
a=a.reshape(3,3)
np.linalg.matrix_rank(a)

2

In [57]:
a=np.arange(1,10)
a=a.reshape(3,3)
np.trace(a)

15

In [58]:
a=np.arange(10,19)
a=a.reshape(3,3)
print(np.linalg.slogdet(a))
a


(0.0, -inf)


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [62]:
a=np.array([[1,2],[3,4]])     #solution of equations x+2y=8 and 3x+4y=18
b=np.array([8,18])
np.linalg.solve(a,b)

array([2., 3.])

In [63]:
a=np.array([[1,2],[3,4]])    
b=np.array([8,18])
c=np.dot(a,b)
c

array([44, 96])

In [64]:
a*b

array([[ 8, 36],
       [24, 72]])